#!/usr/bin/env python3
import os
import sys
import subprocess
import shutil

# Config paths
CONFIG_DIR = os.path.expanduser("~/.config/clicky")
ENV_FILE = os.path.join(CONFIG_DIR, "env.conf")
OUTPUT_PATH = "/tmp/screen.png"

def read_env_conf():
    """Reads the environment configurations generated by setup.sh."""
    config = {}
    if not os.path.exists(ENV_FILE):
        print(f"Warning: Configuration file {ENV_FILE} not found. Using default environment variables.", file=sys.stderr)
        return config
    
    with open(ENV_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, val = line.split("=", 1)
                # Strip quotes
                config[key.strip()] = val.strip().strip('"').strip("'")
    return config

def capture_x11():
    """Captures the screen on X11 session using maim."""
    print("X11 environment detected. Attempting capture with maim...")
    if shutil.which("maim"):
        try:
            subprocess.run(["maim", OUTPUT_PATH], check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running maim: {e}", file=sys.stderr)
    else:
        print("maim not found in PATH.", file=sys.stderr)
    return False

def capture_wayland():
    """Captures the screen on Wayland. Prioritizes grim (silent and fast on wlroots/Hyprland)."""
    print("Wayland environment detected.")
    
    # Check if grim is available (optimal for wlroots / Hyprland)
    if shutil.which("grim"):
        print("Using grim for silent screen capture...")
        try:
            subprocess.run(["grim", OUTPUT_PATH], check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running grim: {e}", file=sys.stderr)
            
    # Fallback to gnome-screenshot if available
    elif shutil.which("gnome-screenshot"):
        print("Using gnome-screenshot as fallback...")
        try:
            subprocess.run(["gnome-screenshot", "-f", OUTPUT_PATH], check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running gnome-screenshot: {e}", file=sys.stderr)
            
    # DBus desktop portal fallback (handles GNOME, KDE, etc.)
    else:
        print("No CLI capture utilities found. Attempting DBus Desktop Portal Screenshot...")
        try:
            # We import pydbus here dynamically so it's only loaded when needed
            from pydbus import SessionBus
            from gi.repository import GLib
            
            bus = SessionBus()
            portal = bus.get("org.freedesktop.portal.Desktop", "/org/freedesktop/portal/desktop")
            
            # Subscribe to Response signal
            loop = GLib.MainLoop()
            success = [False]
            
            def on_response(response_code, results):
                if response_code == 0 and "uri" in results:
                    uri = results["uri"]
                    # URI is typically file:///path/to/screenshot.png
                    if uri.startswith("file://"):
                        src_path = uri[7:]
                        try:
                            shutil.copy(src_path, OUTPUT_PATH)
                            success[0] = True
                        except Exception as e:
                            print(f"Failed to copy portal screenshot to target path: {e}", file=sys.stderr)
                loop.quit()

            # Generate a unique request token
            import uuid
            token = f"clicky_screenshot_{uuid.uuid4().hex[:8]}"
            
            # The portal path to subscribe to signal
            sender = bus.dbus.GetConnectionUnixUser(bus.dbus.GetNameOwner("org.freedesktop.portal.Desktop"))
            # In some setups, we subscribe to the specific request object
            
            # We call Screenshot interface method. 
            # First arg is parent_window (empty string is fine). 
            # Second is options: {'interactive': False} (tries to take it without dialog if permitted)
            # Returns a request handle path
            handle_path = portal.Screenshot("", {"handle_token": token, "interactive": False})
            
            # Subscribe to Response on that request object path
            request_obj = bus.get("org.freedesktop.portal.Desktop", handle_path)
            request_obj.Response.connect(on_response)
            
            # Run event loop to wait for response signal (timeout after 5 seconds)
            GLib.timeout_add(5000, loop.quit)
            loop.run()
            
            return success[0]
        except Exception as e:
            print(f"DBus Portal screenshot failed: {e}", file=sys.stderr)
            
    return False

def main():
    config = read_env_conf()
    session_type = config.get("SESSION_TYPE", "wayland")
    
    # Ensure any old file is removed first
    if os.path.exists(OUTPUT_PATH):
        try:
            os.remove(OUTPUT_PATH)
        except OSError:
            pass

    success = False
    if session_type == "x11":
        success = capture_x11()
    else:
        success = capture_wayland()

    if success and os.path.exists(OUTPUT_PATH):
        print(f"Screenshot successfully captured and saved to: {OUTPUT_PATH}")
        sys.exit(0)
    else:
        print("Error: Failed to capture screen.", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
