#!/usr/bin/env python3
import os
import sys
import subprocess
import shutil

# Config paths
CONFIG_DIR = os.path.expanduser("~/.config/heyclicky")
ENV_FILE = os.path.join(CONFIG_DIR, "env.conf")
OUTPUT_PATH = f"/tmp/heyclicky_screen_{os.getuid()}.png"

def read_env_conf():
    """Reads the environment configurations generated by setup.sh."""
    config = {}
    if not os.path.exists(ENV_FILE):
        print(f"Warning: Configuration file {ENV_FILE} not found. Using default environment variables.", file=sys.stderr)
        return config
    
    with open(ENV_FILE, "r") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                key, val = line.split("=", 1)
                # Strip quotes
                config[key.strip()] = val.strip().strip('"').strip("'")
    return config

def capture_x11():
    """Captures the screen on X11 session with maim, gnome-screenshot, or spectacle."""
    print("X11 environment detected.")
    
    # 1. Try maim
    if shutil.which("maim"):
        print("Attempting capture with maim...")
        try:
            subprocess.run(["maim", OUTPUT_PATH], check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running maim: {e}", file=sys.stderr)
            
    # 2. Try gnome-screenshot
    if shutil.which("gnome-screenshot"):
        print("Attempting capture with gnome-screenshot...")
        try:
            subprocess.run(["gnome-screenshot", "-f", OUTPUT_PATH], check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running gnome-screenshot: {e}", file=sys.stderr)
            
    # 3. Try spectacle
    if shutil.which("spectacle"):
        print("Attempting capture with spectacle...")
        try:
            subprocess.run(["spectacle", "-b", "-m", "-n", "-o", OUTPUT_PATH], check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running spectacle: {e}", file=sys.stderr)
            
    return False

def capture_via_portal():
    """Captures the screen using the DBus Desktop Portal Screenshot API."""
    print("No CLI capture utilities succeeded. Attempting DBus Desktop Portal Screenshot...")
    try:
        # We import pydbus here dynamically so it's only loaded when needed
        from pydbus import SessionBus
        from gi.repository import GLib
        
        bus = SessionBus()
        portal = bus.get("org.freedesktop.portal.Desktop", "/org/freedesktop/portal/desktop")
        
        # Subscribe to Response signal
        loop = GLib.MainLoop()
        success = [False]
        
        def on_response(response_code, results):
            if response_code == 0 and "uri" in results:
                uri = results["uri"]
                # URI is typically file:///path/to/screenshot.png
                if uri.startswith("file://"):
                    src_path = uri[7:]
                    try:
                        shutil.copy(src_path, OUTPUT_PATH)
                        success[0] = True
                    except Exception as e:
                        print(f"Failed to copy portal screenshot to target path: {e}", file=sys.stderr)
            loop.quit()

        # Generate a unique request token
        import uuid
        token = f"heyclicky_screenshot_{uuid.uuid4().hex[:8]}"
        
        # We call Screenshot interface method. 
        # First arg is parent_window (empty string is fine). 
        # Second is options: {'interactive': False} (tries to take it without dialog if permitted)
        # Returns a request handle path
        handle_path = portal.Screenshot("", {"handle_token": token, "interactive": False})
        
        # Subscribe to Response on that request object path
        request_obj = bus.get("org.freedesktop.portal.Desktop", handle_path)
        request_obj.Response.connect(on_response)
        
        # Run event loop to wait for response signal (timeout after 5 seconds)
        GLib.timeout_add(5000, loop.quit)
        loop.run()
        
        return success[0]
    except Exception as e:
        print(f"DBus Portal screenshot failed: {e}", file=sys.stderr)
        return False

def capture_wayland():
    """Captures the screen on Wayland. Prioritizes native tool based on XDG_CURRENT_DESKTOP."""
    print("Wayland environment detected.")
    desktop = os.environ.get("XDG_CURRENT_DESKTOP", "").lower()
    
    # 1. KDE Plasma -> Prioritize spectacle
    if "kde" in desktop or "plasma" in desktop:
        if shutil.which("spectacle"):
            print("KDE detected. Using spectacle for silent screen capture...")
            try:
                subprocess.run(["spectacle", "-b", "-m", "-n", "-o", OUTPUT_PATH], check=True)
                return True
            except subprocess.CalledProcessError as e:
                print(f"Error running spectacle: {e}", file=sys.stderr)
        else:
            print("KDE detected but spectacle not found in PATH.", file=sys.stderr)
            
    # 2. GNOME -> Prioritize gnome-screenshot
    elif "gnome" in desktop or "unity" in desktop or "ubuntu" in desktop:
        if shutil.which("gnome-screenshot"):
            print("GNOME/Ubuntu detected. Using gnome-screenshot...")
            try:
                subprocess.run(["gnome-screenshot", "-f", OUTPUT_PATH], check=True)
                return True
            except subprocess.CalledProcessError as e:
                print(f"Error running gnome-screenshot: {e}", file=sys.stderr)
        else:
            print("GNOME detected but gnome-screenshot not found in PATH.", file=sys.stderr)

    # 3. wlroots/Hyprland/Sway -> Prioritize grim
    # Check for grim (optimal for wlroots / Hyprland)
    if shutil.which("grim"):
        print("Using grim for silent screen capture...")
        try:
            monitor_name = None
            if shutil.which("jq"):
                if shutil.which("hyprctl"):
                    try:
                        res = subprocess.run(
                            "hyprctl monitors -j | jq -r '.[] | select(.focused) | .name'",
                            shell=True, capture_output=True, text=True, check=True
                        )
                        monitor_name = res.stdout.strip()
                    except Exception:
                        pass
                if not monitor_name and shutil.which("swaymsg"):
                    try:
                        res = subprocess.run(
                            "swaymsg -t get_outputs | jq -r '.[] | select(.focused) | .name'",
                            shell=True, capture_output=True, text=True, check=True
                        )
                        monitor_name = res.stdout.strip()
                    except Exception:
                        pass

            if monitor_name:
                print(f"Focused monitor resolved: {monitor_name}. Capturing active monitor...")
                subprocess.run(["grim", "-o", monitor_name, OUTPUT_PATH], check=True)
                return True
            
            # Fallback to standard grim capture (capturing whole desktop)
            subprocess.run(["grim", OUTPUT_PATH], check=True)
            return True
        except subprocess.CalledProcessError as e:
            print(f"Error running grim: {e}", file=sys.stderr)
            
    # 4. Fallback: try other CLI tools regardless of detected desktop
    for tool, cmd in [
        ("spectacle", ["spectacle", "-b", "-m", "-n", "-o", OUTPUT_PATH]),
        ("gnome-screenshot", ["gnome-screenshot", "-f", OUTPUT_PATH]),
    ]:
        if shutil.which(tool):
            print(f"Attempting fallback capture with {tool}...")
            try:
                subprocess.run(cmd, check=True)
                return True
            except subprocess.CalledProcessError:
                pass
                
    # 5. Final Fallback: DBus desktop portal
    return capture_via_portal()

def main():
    config = read_env_conf()
    session_type = config.get("SESSION_TYPE", "wayland")
    
    # Ensure any old file is removed first
    if os.path.exists(OUTPUT_PATH):
        try:
            os.remove(OUTPUT_PATH)
        except OSError:
            pass

    success = False
    if session_type == "x11":
        success = capture_x11()
    else:
        success = capture_wayland()

    if success and os.path.exists(OUTPUT_PATH):
        print(f"Screenshot successfully captured and saved to: {OUTPUT_PATH}")
        sys.exit(0)
    else:
        print("Error: Failed to capture screen.", file=sys.stderr)
        sys.exit(1)

if __name__ == "__main__":
    main()
